_target_: tmrl.models.flow.ContextSmoothedFlowPolicy
obs_dim: ${dataset.obs_dim}
action_len: ${dataset.action_len}
action_dim: ${dataset.action_dim}
goal_dim: ${dataset.goal_dim}
context_dim: ${dataset.goal_dim}

defaults:
  - flow
