# @package _global_
debug: false
seed: 42

paths:
  project_dir: ${hydra:runtime.cwd}
  data_dir: ${paths.project_dir}/datasets
  results_dir: ${paths.project_dir}/results
  wandb_dir: ${paths.project_dir}/wandb
  ckpt_dir: ${paths.project_dir}/checkpoints

use_wandb: false
wandb:
  entity: null   # set to your W&B entity, or leave null to use your default
  name: "${hydra:runtime.choices.model}_${hydra:runtime.choices.dataset}_${now:%m%d_%H%M}"
  tags: null
  dir: ${paths.wandb_dir}

optimizer:
  lr: 3e-4
  weight_decay: 1e-6
  betas: [0.95, 0.999]
  eps: 1e-8

scheduler:
  name: "constant"
