# training
train_steps: 10_000
capacity: ${train_steps}
eval_interval: 1_000
render_videos: true
ckpt: null

checkpoint:
  save_interval: ${eval_interval}
  resume_path: null

# sac
n_envs: 1
n_evals: 10
n_viz: 5
skip_first: false
action_exec_len: 5 # query freq: from DSRL, for libero

learning_starts: 100
use_autotune: true
use_success_buffer: true

# method
method: tmrl    # tmrl | dsrl
noise_bound: 1.0 # sac noise action bound
context_noise_bound: 1.0 # context noise bound
timestep_max: 1.0
actor_action_dim: 32

remote_robot:
  host: null
  port: null
  connect_timeout: 300.0

optimizer:
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.95, 0.999]
  eps: 1e-8

defaults:
  - base
  - dataset: widowx
  - model: sac_robot
  - _self_