# training
train_steps: 200_000
log_interval: 25_000
save_interval: 25_000

# postbc
use_postbc: false
postbc_alpha: 1.0
postbc_ensemble_size: 10
postbc_ensemble_epochs: 1000

defaults:
  - base
  - model: nfp
  - dataset: pointmaze-large
  - _self_
