defaults:
  - submitit_slurm

# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 5000
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

partition: gpu-l40
gres: gpu:l40:1
account: weirdlab

qos: null
comment: null
cpus_per_task: 16
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {
  mem: 128G,
  # begin: now+1hours
}
array_parallelism: 256

setup:
  - export MUJOCO_GL=egl